// Generated by LiveScript 1.2.0
module.exports = function(){
  var express, app;
  express = require('express');
  app = express();
  app.get('/:action', function(req, res){
    console.log(req.params);
    return res.send(req.params.action);
  });
  return app;
}();
