// Generated by LiveScript 1.2.0
module.exports = function(){
  var app;
  app = process.express();
  app.get('/:action', function(req, res){
    console.log(req.params);
    return res.send(req.params.action);
  });
  return app;
}();
