// Generated by LiveScript 1.2.0
var responseTime, app, server;
responseTime = require('response-time');
process.express = require('express');
app = process.express();
app.use(responseTime()).use('/api', require('./api.js'));
if (process.env.http != null || process.env.PORT != null) {
  console.log('started on port ' + (process.env.http || process.env.PORT) + ' at ' + new Date(Date.now()));
  server = app.listen(process.env.http || process.env.PORT);
} else {
  console.error('no port specified please use --http <port> / http or port environment variable');
  process.exit();
}